INSERT INTO CLASSROOMS (NUMBER, BUILDING, CAPACITY) VALUES ('106','23',30);
INSERT INTO CLASSROOMS (NUMBER, BUILDING, CAPACITY) VALUES ('211','23',50);
INSERT INTO CLASSROOMS (NUMBER, BUILDING, CAPACITY) VALUES ('321','23',30);
INSERT INTO CLASSROOMS (NUMBER, BUILDING, CAPACITY) VALUES ('401','24',100);
INSERT INTO CLASSROOMS (NUMBER, BUILDING, CAPACITY) VALUES ('305','24',30);
