DROP TABLE IF EXISTS CLASSROOMS;

CREATE TABLE IF NOT EXISTS CLASSROOMS
(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NUMBER VARCHAR(10),
    BUILDING VARCHAR(10),
    CAPACITY INTEGER NOT NULL,
    CONSTRAINT CLASSROOMS_ID_PKEY PRIMARY KEY (ID)
);
