INSERT INTO GROUPS (NAME) VALUES ('1-D-31');
INSERT INTO GROUPS (NAME) VALUES ('1-L-32');
INSERT INTO GROUPS (NAME) VALUES ('2-M-43');
INSERT INTO GROUPS (NAME) VALUES ('3-F-64');
INSERT INTO GROUPS (NAME) VALUES ('3-SK-90');