DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE IF NOT EXISTS STUDENTS
(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    GROUP_ID INTEGER DEFAULT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    CONSTRAINT STUDENTS_ID_PKEY PRIMARY KEY (ID),
    --CONSTRAINT GROUPS_ID_FKEY FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID) 
);
