INSERT INTO STUDENTS (FIRSTNAME,LASTNAME,GROUP_ID) VALUES ('ANDREY','IMSHENIK',1);
INSERT INTO STUDENTS (FIRSTNAME,LASTNAME,GROUP_ID) VALUES ('IVAN','STEPANOV',2);
INSERT INTO STUDENTS (FIRSTNAME,LASTNAME,GROUP_ID) VALUES ('GEORGY','TEPLOV',3);
INSERT INTO STUDENTS (FIRSTNAME,LASTNAME,GROUP_ID) VALUES ('MARY','LE',4);
INSERT INTO STUDENTS (FIRSTNAME,LASTNAME,GROUP_ID) VALUES ('ELENA','YAKOVLEVA',5);
