DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE IF NOT EXISTS TEACHERS
(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    PASSPORT VARCHAR(50),
    CONSTRAINT TEACHERS_ID_PKEY PRIMARY KEY (ID),
);
