INSERT INTO TEACHERS (FIRSTNAME,LASTNAME,PASSPORT) VALUES ('ANDREY FEDOROVICH','SMIKOV','AA-11111');
INSERT INTO TEACHERS (FIRSTNAME,LASTNAME,PASSPORT) VALUES ('VIKTOR SERGEEVICH','MOISEEV','AA-22222');
INSERT INTO TEACHERS (FIRSTNAME,LASTNAME,PASSPORT) VALUES ('DMITRY VASILYEVICH','BEREZHNOY','AA-33333');
INSERT INTO TEACHERS (FIRSTNAME,LASTNAME,PASSPORT) VALUES ('BORIS LEONIDOVICH','BOBRYSHEV','AA-44444');
INSERT INTO TEACHERS (FIRSTNAME,LASTNAME,PASSPORT) VALUES ('OLGA VALENTINOVNA','TELITSYNA','AA-55555');
